#!/usr/bin/env python
#
#   Copyright 2022 Kevin T. Chu
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
"""
Script for counting current puzzles.
"""

# --- Imports

# Standard library
import glob
import os

# External packages
import typer


# --- Main program

def main() -> None:
    """
    Count current puzzles.
    """
    puzzles_dirpath = os.path.join(os.path.dirname(os.path.dirname(__file__)),
                                   "puzzles")
    markdown_files = [
        os.path.basename(path)
        for path in glob.glob(os.path.join(puzzles_dirpath, "*.md"))]

    puzzle_files = [file_ for file_ in markdown_files if "-" not in file_]
    typer.echo(len(puzzle_files))


# --- Run app

if __name__ == "__main__":
    typer.run(main)
